import { Request, Response } from 'express';
import * as BookingService from '../service/booking.service';
import Booking from '../models/booking.module';

export const createBooking = async (req: Request, res: Response) => {
  const { flightId, seatNumber, location } = req.body;
  const userId = (req as any).user?.uid;
  const newBooking = new Booking(
    '', // ID will be generated by the service or Firestore
    userId,
    flightId,
    seatNumber,
    'confirmed',
    new Date(),
    location
  );
  const result = await BookingService.createBooking(newBooking, userId);
  res.status(201).json(result);
};

export const getBookingById = async (req: Request, res: Response) => {
    try {
      const result = await BookingService.getBooking(req.params.id);
      res.status(200).json(result);
    } catch (error) {
      res.status(404).json({ message: 'Booking not found' });
    }
  };
  

export const updateBooking = async (req: Request, res: Response) => {
  const result = await BookingService.updateBooking(req.params.id, req.body);
  res.status(200).json(result);
};

export const deleteBooking = async (req: Request, res: Response) => {
  const result = await BookingService.deleteBooking(req.params.id);
  res.status(200).json(result);
};
